### ISSUE TITLE
A problem about dynamic_proxy. 

### ISSUE THREAD

**Issue by Domingor** [mohuishou/go-design-pattern#11]
There is a problem that the dynamic_proxy, when I run this function “generate("./static_proxy.go”)”, I got a template string, but how should I run it, which is template string? Is this template a proxy? It really seemed like a go code, but I now just got a string template and I don’t know how to run this template string. right? 
So how to change this template string to a real go code? I mean running it, so I can see the information in the console.

**Comment by mohuishou** [comment]
This is just an example. The dynamic_proxy is implemented through code generation, so in order to make it work, the generated string needs to be written into a file, such as ./static_proxy_gen.go. 
If you can read Chinese articles, you can refer to my previous blog post for some corresponding explanations.
https://lailin.xyz/post/proxy.html#Go-Generate-%E5%AE%9E%E7%8E%B0-%E2%80%9C%E5%8A%A8%E6%80%81%E4%BB%A3%E7%90%86%E2%80%9D

**Comment by Domingor** [comment]
I see, thank you very much. I've been reading your blog for about three weeks now. And I've got some questions I want to figure out.&nbsp;
By the way, I am an engineer working on IoT development. I can read Chinese articles because I am an ethnic Chinese. And the blogs you have mentioned to me, I will learn about them this week. ​Also, I am sure your blog will help me a lot. I've been using Go for development recently. This is my website, which I made when I was in school.

&nbsp;


码农
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mohuishou/go-design-pattern"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 中午1:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mohuishou/go-design-pattern] A problem about dynamic_proxy.  (Issue #11)





 
This is just an example. The dynamic_proxy is implemented through code generation, so in order to make it work, the generated string needs to be written into a file, such as ./static_proxy_gen.go.
 If you can read Chinese articles, you can refer to my previous blog post for some corresponding explanations.
 https://lailin.xyz/post/proxy.html#Go-Generate-%E5%AE%9E%E7%8E%B0-%E2%80%9C%E5%8A%A8%E6%80%81%E4%BB%A3%E7%90%86%E2%80%9D

**Comment by mohuishou** [comment]
- The term “dynamic proxy” here is in quotation marks because typically when we talk about dynamic proxies, we are referring to runtime proxies. However, the implementation here is based on code generation using go generate, which is a compile-time approach.
- I have closed this issue for now. If there are any further problems, please feel free to open a new one or reopen this one.
