### ISSUE TITLE
Web Server Design Pattern

### ISSUE THREAD

**Issue by kalengbekas** [mohuishou/go-design-pattern#8]
which design pattern is suitable for web server ? if the web server directory is :

- route
- db
- controller
- model
- entity

**Comment by shanghai-Jerry** [comment]
it's more about framework, not design pattern i think.

**Comment by mohuishou** [comment]
In web frameworks, many design patterns are used, but they are closely related to the framework’s design. 
For example,
- in routing, we often use middleware, which involves the use of the Chain of Responsibility pattern. 
- During project initialization, we often use the Factory pattern, Singleton pattern, and in more complex projects, we may use Dependency Injection. 

The specific pattern used depends on the scenario, and it’s important to focus on design principles such as SOLID, rather than worrying about which pattern to use.

**Comment by mohuishou** [comment]
If you can read Chinese, you may be interested in checking out my previous articles on Golang engineering.
https://lailin.xyz/post/go-training-week4-clean-arch.html

**Comment by kalengbekas** [comment]
> If you can read Chinese, you may be interested in checking out my previous articles on Golang engineering. https://lailin.xyz/post/go-training-week4-clean-arch.html

This is an awesome articles for me. Thank you for sharing.
